#### Import Libraries

In [1]:
import pandas as pd
import numpy as np

#### Q1: What's the version of NumPy that you installed?

In [2]:
np.__version__

'1.21.5'

#### Read in data

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv")

In [4]:
df.head(2)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650

#### Q2: How many records are in the dataset?

In [5]:
df.shape

(11914, 16)

#### Q3: Who are the most frequent car manufacturers (top-3) according to the dataset?

In [6]:
df['Make'].value_counts().head(n = 3)

Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

#### Q4: What's the number of unique Audi car models in the dataset?

In [7]:
df[df['Make'] == "Audi"]['Model'].nunique()

34

#### Q5: How many columns in the dataset have missing values?

In [8]:
print(df.isnull().sum()[df.isnull().sum() >= 1], 
      'number of columns with missing values is', df.isnull().sum()[df.isnull().sum() >= 1].shape[0])

Engine Fuel Type       3
Engine HP             69
Engine Cylinders      30
Number of Doors        6
Market Category     3742
dtype: int64 number of columns with missing values is 5


#### Q6

#### 1. Find the median value of "Engine Cylinders" column in the dataset.

In [9]:
median_value = df['Engine Cylinders'].median()
median_value

6.0

#### 2. Next, calculate the most frequent value of the same "Engine Cylinders".

In [10]:
modal_value = df['Engine Cylinders'].mode()
modal_value

0    4.0
Name: Engine Cylinders, dtype: float64

#### 3. Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.

In [11]:
df['Engine Cylinders'].fillna(modal_value, inplace=True)

#### 4. Now, calculate the median value of "Engine Cylinders" once again.

In [12]:
df['Engine Cylinders'].median()

6.0

#### Q7

In [13]:
lotus_cars = df[df['Make'].str.lower() == 'lotus']
lotus_cars.shape

(29, 16)

In [14]:
lotus_cars.head(3)

Make  Model  Year             Engine Fuel Type  Engine HP  \
3912  Lotus  Elise  2009  premium unleaded (required)      189.0   
3913  Lotus  Elise  2009  premium unleaded (required)      218.0   
3914  Lotus  Elise  2009  premium unleaded (required)      189.0   

      Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
3912               4.0            MANUAL  rear wheel drive              2.0   
3913               4.0            MANUAL  rear wheel drive              2.0   
3914               4.0            MANUAL  rear wheel drive              2.0   

              Market Category Vehicle Size Vehicle Style  highway MPG  \
3912  Exotic,High-Performance      Compact   Convertible           27   
3913  Exotic,High-Performance      Compact   Convertible           26   
3914  Exotic,High-Performance      Compact   Convertible           27   

      city mpg  Popularity   MSRP  
3912        21         613  43995  
3913        20         613  54990  
3914        21         613  47250

In [15]:
X = lotus_cars[["Engine HP", "Engine Cylinders"]].drop_duplicates().values

In [16]:
print(X.T,'\n','\n',X)

[[189. 218. 217. 350. 400. 276. 345. 257. 240.]
 [  4.   4.   4.   8.   6.   6.   6.   4.   4.]] 
 
 [[189.   4.]
 [218.   4.]
 [217.   4.]
 [350.   8.]
 [400.   6.]
 [276.   6.]
 [345.   6.]
 [257.   4.]
 [240.   4.]]


In [17]:
#### Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
XTX = X.T.dot(X)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [18]:
#### Invert XTX
XTX_inverse = np.linalg.inv(XTX)
XTX_inverse

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [19]:
#### confirm dot product
np.around(XTX.dot(XTX_inverse)).astype(int)

array([[1, 0],
       [0, 1]])

In [20]:
## Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])

In [21]:
XTX_inverse

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [22]:
w = y.dot(X.dot(XTX_inverse))
w

array([  4.59494481, -63.56432501])